menu:
- {name: 'Research', url: '/research'}
- {name: 'Publications', url: '/publications'}
- {name: 'CV', url: '/cv/Donghyun_Sohn_CV.pdf'}
#- {name: 'Backgrounds', url: '/backgrounds'}
#- {name: 'Blogs', url: '/blogs'}

research:
- {name: 'Disk-based BACF Tree for Clustering Massive Dataset', url: 'BACF'}
- {name: 'A real-time monitoring system using OpenPose', url: 'OpenPose'}

backgrounds:
- {name: 'Data Systems Seminar (Fall 2022)', url: 'Data Systems Seminar'}
- {name: 'Database Basics', url: 'Database Basics'}
- {name: 'CMU 15-445/645 Intro to Database Systems (Fall 2021)', url: 'CMU 15.445.645'}
- {name: 'Personal Paper Review', url: 'PPR'}
#- {name: 'MIT 6.875 Foundations of Cryptography (Fall 2021)', url: 'MIT 6.875'}

social:
- {icon: 'github', link: 'https://github.com/donghyun-sohn'}
- {icon: 'twitter', link: 'https://twitter.com/Dustin_DHSohn'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/bulelion37/'}

academic:
- {icon: 'scholar', link: 'https://scholar.google.com/citations?view_op=list_works&hl=ko&authuser=1&user=xp3ZJPgAAAAJ'}
